# Generated by Django 4.0.4 on 2022-05-16 16:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='servers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ServerType', models.CharField(blank=True, choices=[('Production', 'Production'), ('Staging', 'Staging'), ('Development', 'Development'), ('Others', 'Others')], default='', max_length=20, null=True)),
                ('DBType', models.CharField(blank=True, choices=[('ASE', 'ASE'), ('REP', 'REP'), ('IQ', 'IQ'), ('MySQL', 'MySQL'), ('MSSQL', 'MSSQL'), ('Others', 'Others')], default='', max_length=20, null=True)),
                ('ServerName', models.CharField(blank=True, default='', max_length=120, null=True)),
                ('DBVersion', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('HostName', models.CharField(blank=True, default='', max_length=120, null=True)),
                ('HostIP', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('HostVersion', models.CharField(blank=True, default='', max_length=120, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='site',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('SiteName', models.CharField(blank=True, default='', max_length=120, null=True)),
                ('URL_Link', models.URLField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HostName', models.CharField(blank=True, default='', max_length=120, null=True)),
                ('ServerName', models.CharField(blank=True, default='', max_length=120, null=True)),
                ('CreatedOn', models.DateTimeField(auto_now_add=True, null=True)),
                ('PerformedAt', models.DateTimeField(null=True)),
                ('PerformedBy', models.CharField(blank=True, choices=[('snegalur', 'snegalur'), ('vinay', 'vinay'), ('saikat', 'saikat')], max_length=20, null=True)),
                ('ServerType', models.CharField(blank=True, choices=[('Production', 'Production'), ('Staging', 'Staging'), ('Development', 'Development'), ('other', 'other')], default='', max_length=20, null=True)),
                ('Comments', models.TextField(blank=True, default='', max_length=10000, null=True)),
                ('EnteredBy', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
