# Generated by Django 4.0.4 on 2022-05-18 16:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('eventlogapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='dt_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
