# Generated by Django 4.0.4 on 2022-05-18 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventlogapp', '0002_details_dt_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='PerformedAt',
        ),
        migrations.RemoveField(
            model_name='details',
            name='dt_time',
        ),
    ]
