# Generated by Django 4.0.4 on 2022-05-18 16:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('eventlogapp', '0003_remove_details_performedat_remove_details_dt_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='PerformedAt',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
