# Generated by Django 4.0.4 on 2022-05-21 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventlogapp', '0004_details_performedat'),
    ]

    operations = [
        migrations.AddField(
            model_name='servers',
            name='vCPUs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servers',
            name='ServerName',
            field=models.CharField(default='', max_length=120, unique=True),
        ),
    ]
