# Generated by Django 4.0.4 on 2022-05-27 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventlogapp', '0005_servers_vcpus_alter_servers_servername'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='ServerType',
            field=models.CharField(blank=True, choices=[('Production', 'Production'), ('Staging', 'Staging'), ('Development', 'Development'), ('Pre-Prod', 'Pre-Prod'), ('Decommissioned', 'Decommissioned')], default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='servers',
            name='ServerName',
            field=models.CharField(blank=True, default='', max_length=120, unique=True),
        ),
    ]
