# Generated by Django 4.0.4 on 2022-05-30 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventlogapp', '0006_alter_details_servertype_alter_servers_servername'),
    ]

    operations = [
        migrations.AddField(
            model_name='servers',
            name='VIPIp',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='servers',
            name='VIPName',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='servers',
            name='ServerType',
            field=models.CharField(blank=True, choices=[('Production', 'Production'), ('Staging', 'Staging'), ('Development', 'Development'), ('Pre-Prod', 'Pre-Prod'), ('Decommissioned', 'Decommissioned')], default='', max_length=20, null=True),
        ),
    ]
