# Generated by Django 4.0.4 on 2022-06-07 18:43

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventlogapp', '0009_alter_details_comments_alter_details_performedby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='Comments',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
